version: '3.1'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  product-service:
    build: ./product-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mongo:
    image: mongo:4.2

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
